name: "🚀 RELEASE: To WordPress.org"
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          GITHUB_TOKEN: ${{{{raw-helper}}}}{{ secrets.GITHUB_TOKEN }}{{{{/raw-helper}}}}
          SVN_USERNAME: ${{{{raw-helper}}}}{{ secrets.SVN_USERNAME }}{{{{/raw-helper}}}}
          SVN_PASSWORD: ${{{{raw-helper}}}}{{ secrets.SVN_PASSWORD }}{{{{/raw-helper}}}}
          SLUG: "{{slug}}"
